spring.application.name=echoroom_backend
server.address=0.0.0.0
server.port=8080
app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*,http://192.168.29.3:*,https://*.pages.dev
socketio.host=0.0.0.0
socketio.port=9092
socketio.origin=*
